version: '3.8'
# You can just enable docker for psql database, Or run whole project on docker container

# Database service
services:
  treadx-db:
    image: postgres:latest
    container_name: treadx-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: treadx
      PGDATA: /var/lib/postgresql/data # Internal path where Postgres stores data
    ports:
      - "5432:5432" # Maps container port 5432 to host port 5432 (optional for direct access)
    networks:
      - treadx-net
    restart: unless-stopped
    volumes:
      # This mount for /docker-entrypoint-initdb.d is for *initial* database setup,
      # typically for a V1 script that sets up the very first database state
      # or creates the database itself if not handled by environment variables.
      # Flyway will handle subsequent schema changes.
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
      # Named Volume for Persistent Database Data (CRUCIAL FOR DATA PERSISTENCE & RESTORATION)
      - treadx_pg_data:/var/lib/postgresql/data # Maps internal PGDATA to a named Docker volume
    healthcheck: # IMPORTANT: This ensures the DB is truly ready before apps connect
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Give the DB some initial time to come up

  # application service
  treadx-app:
    build: . # Builds the Docker image from the Dockerfile in the current directory
    image: treadx-app # Name for your built Docker image
    depends_on:
      # treadx-app will start ONLY AFTER treadx-db is healthy
      treadx-db:
        condition: service_healthy
    container_name: treadx-backend
    ports:
      - "9003:9003" # Maps container port 9003 to host port 9003
    environment:
      # Database connection details, using the Docker Compose service name 'treadx-db' as the hostname
      SPRING_DATASOURCE_URL: jdbc:postgresql://treadx-db:5432/treadx
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DATABASE: treadx
      # Ensure Flyway is enabled (though usually auto-detected)
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_FLYWAY_LOCATIONS: "classpath:/db/migration"
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
    networks:
      - treadx-net # Connects to the shared network

networks:
  treadx-net:
    external: true # Assumes this network is created manually (e.g., docker network create treadx-net)

# Define the named volume for data persistence
volumes:
  treadx_pg_data: # This is the named volume that Docker manages on your host