version: '3.8'
# You can just enable docker for psql database, Or run whole project on docker container

# Database service
services:
  treadx-db:
    image: postgres:latest
    container_name: treadx-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: treadx
      PGDATA: /var/lib/postgresql/data # This is the internal path where Postgres stores data
    ports:
      - "5432:5432"
    networks:
      - treadx-net
    restart: unless-stopped
    volumes:
      # Mount for SQL Initialization Scripts (for first-time setup)
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
      # Named Volume for Persistent Database Data (THIS IS CRUCIAL FOR DATA PERSISTENCE)
      - treadx_pg_data:/var/lib/postgresql/data # Maps internal PGDATA to a named volume on the Docker host

# application service
#
  treadx-app:
    build: .
    image: treadx-app
    depends_on:
      - treadx-db
    container_name: treadx-backend
    ports:
      - "9003:9003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://treadx-db:5432/treadx
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DATABASE: treadx
    networks:
      - treadx-net

networks:
  treadx-net:
    external: true

# Define the named volume for data persistence
volumes:
  treadx_pg_data: # This is the named volume that Docker manages on your host