server:
  port: 9003

spring:
  application:
    name: TreadX
  datasource:
    url: jdbc:postgresql://localhost:5432/treadx
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    name: treadx
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      format_sql: true
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    show-sql: true
jwtKey: 7402bb3c24c35f15d1a7f1422078d9c1a4d9ebf1a276ff01ac84e6407625532e